- spreadsheetID: "1K8_wzB05oFU7r9VlGBuKmjyjiXrKQUO8hyDT5JHOauI"
  sheetName: "Talks"
  startRow: 2
  columns:
    - column: A
      name: "owner"
      required: true
    - column: B
      name: "event"
      required: true
    - column: C
      name: "status"
      required: true
      exclude:
        - "Withdrawn"
        - "Won't Do"
        - "Rejected"
    - column: D
      name: "startdate"
      required: true
    - column: E
      name: "enddate"
      required: true
    - column: F
      name: "pubpri"
    - column: I
      name: "type"
      required: true
    - column: J
      name: "location"
  endpoint: "talks.ics"
  event:
    dtstart: "[startdate]"
    dtend: "[enddate]"
    summary: "TALK: [status]: [event] ([owner])"
    description: "Public/Private: [pubpri]\nType: [type]"
    location: "[location]"
- spreadsheetID: "1K8_wzB05oFU7r9VlGBuKmjyjiXrKQUO8hyDT5JHOauI"
  sheetName: "BootCamps"
  startRow: 33 # Start with FY 2021 bootcamps
  columns:
    - column: C
      name: "bootcamp"
      required: true
    - column: D
      name: "status"
      required: true
      exclude:
        - "Won't Do"
        - "Rejected"
    - column: B
      name: "lead"
    - column: E
      name: "manager"
    - column: F
      name: "shadow"
    - column: H
      name: "location"
    - column: I
      name: "length"
    - column: J
      name: "date"
      required: true
      exclude:
        - "TBD"
    - column: K
      name: "pubpri"
  endpoint: "bootcamps.ics"
  event:
    dtstart: "[date]"
    dtend: "[date]"
    summary: "BOOTCAMP: [status]: [bootcamp] ([lead])"
    description: "Length: [length]\nPublic/Private: [pubpri]\nLead: [lead]\nManager: [manager]\nShadow/Partner: [shadow]"
    location: "[location]"
